name: Check JIRA ID

on:
   pull_request:
    types: [synchronize, opened, reopened]
    branches:
      - "main"
      - "release-[0-9]+.[0-9]+"
   push:
    branches:
      - "main"  
      - "release-[0-9]+.[0-9]+"

jobs:
  check_jira_id:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check JIRA ID
        run: |
          commit_message=$(git log --format=%s -n 1 ${{ github.sha }})
          echo $commit_message
          jira_pattern="\\bJIRA-\\d+\\b"

          if [[ ! $commit_message =~ $jira_pattern ]]; then
            echo "Error: Commit message must have a valid JIRA ticket ID."
            exit 1
          fi

